### ISSUE TITLE
`brew readall` fails on poker-emacs.rb (Linux)

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-emacs#150]
Error: problem in /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-emacs/Formula/poker-emacs.rb

compile error

    /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-emacs/Formula/poker-emacs.rb:33: syntax error, unexpected '.', expecting kEND

                     .strip.gsub(/[()"]/, "")

                      ^

    /home/travis/.linuxbrew/Library/Taps/homebrew/homebrew-emacs/Formula/poker-emacs.rb:34: syntax error, unexpected '.', expecting kEND

                     .split(" ").length

                      ^

See https://travis-ci.org/Homebrew/homebrew-emacs/jobs/100735594

This is one of the few remaining problems with Linuxbrew's Travis build.

**Comment by dunn** [comment]
I've noticed that too; any idea why it's only on Linux?

**Comment by rwhogg** [comment]
It appears to be because of a version difference, not an OS difference.

Using brew ruby (2.3) and Ubuntu 14.04 ruby (1.9.3), I get no problems. Using a ruby-build built 1.8.7 (the same version Travis uses, and thus presumably what Ubuntu 12.04 ships with), I get the same problem Travis does. 

Linuxbrew officially supports 1.8.6 and higher, so by that logic this installation script is broken. Still, I'm not sure continuing to support 1.8.6+ is a good idea, since 1.8.7 [is itself unsupported](https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/). The website spells this out pretty clearly:
```
     Now, a majority of you are using Ruby 1.9.x or 2.0.0 (IF NOT PLEASE DO)
```

I had this exact same debate with respect to Java 7 versus Java 8 [here](https://github.com/validator/validator/issues/206) just a few days ago and argued for the *opposite* side at first but I think the situation here is different. Anyone who's installed Homebrew can fairly easily `brew install` either `ruby-build` or just plain `ruby`. The only real need, IMO, is for Linuxbrew core code to support older versions of ruby just long enough for people to install one of those two packages. We can then say that *this tap* only supports 1.9+.

@sjackman, you suggested in https://github.com/Homebrew/linuxbrew/issues/438 that you didn't " feel too bad about dropping support for old versions of Ruby". Do you have any opinions on this matter?

I'm more than happy to add additional entries to the Travis matrix or to change the existing ones to test against different versions of Ruby, but I have to know what you two think should be officially supported (you're the maintainers after all!)

**Comment by sjackman** [comment]
I'm fine with dropping support for older versions of Ruby. It is nice if the user can use an older version of Ruby to bootstrap and eventually `brew install ruby`, but there are other ways to install a newer version of Ruby, and it could potentially be automated by the `install` script.

**Comment by dunn** [comment]
Homebrew hasn't dropped support for 1.8 yet, so we should probably still fix that.  Is it just an unsupported syntax style?

**Comment by sjackman** [comment]
Yeah, I think so. I suspect concatenating the three lines to a single line would resolve this (untested).

https://github.com/Homebrew/homebrew-emacs/blob/master/Formula/poker-emacs.rb#L32-L34
```ruby
    assert_equal 52, shell_output("emacs -Q --batch -l #{testpath}/test.el")
                     .strip.gsub(/[()"]/, "")
                     .split(" ").length
```

**Comment by xu-cheng** [comment]
@sjackman Actually, dropping support for Ruby 1.8 is much easier on Linuxbrew land. While I'm stilling working on portable ruby for old OS X, on Linux you can use [portable Ruby interpreter](http://traveling-ruby.s3-us-west-2.amazonaws.com/list.html) from [traveling-ruby](https://github.com/phusion/traveling-ruby) directly.

@dunn To make syntax compatible with Ruby 1.8, all you need to do is putting dot in the end of line as such
```ruby
assert_equal 52, shell_output("emacs -Q --batch -l #{testpath}/test.el").
                     strip.gsub(/[()"]/, "").
                     split(" ").length
```

**Comment by dunn** [comment]
@xu-cheng That's what I suspected, thanks!

**Comment by dunn** [comment]
Hopefully the CI will catch these in future, until we do ditch 1.8.  Thanks again!

**Comment by rwhogg** [comment]
@dunn if we're going to keep supporting 1.8, how about I add a new Mac entry into Travis that runs 1.8?

Sure, the Linux build will catch these, but it's set to allow failures.

**Comment by dunn** [comment]
Yeah, core already does that so take a look at that Travis config: https://github.com/Homebrew/homebrew/blob/master/.travis.yml
