### ISSUE TITLE
Willing to take PMD Emacs integration?

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-emacs#157]
I've packaged PMD integration for Emacs at https://github.com/rwhogg/homebrew-emacs/blob/master/Formula/pmd-emacs.rb

I originally put it in my personal tap because it had insufficient stars/forks/watchers, but upon reflection I considered that a) since it's part of the same organization that releases PMD proper and b) PMD is already in the main tap that you might want it anyways.

Would you be interested in including it, or should I keep it in my personal tap?

**Comment by dunn** [comment]
My only reservation is that the last commit was almost two years ago; do you expect they'll continue to keep it up-to-date if there are breakages or bugs reported?

**Comment by rwhogg** [comment]
The maintainer responded and said he is happy to maintain pmd-emacs. He also explained that the reason it has so few commits is that, since it just interacts with PMD over the command line, breaking changes that actually require updates are rare.

With that in mind, I'll try and clean up the formula for distribution and submit a PR, hopefully later today.

**Comment by dunn** [comment]
Thanks!
