### ISSUE TITLE
dash sha256sum wrong.

### ISSUE THREAD

**Issue by jiegec** [Homebrew/homebrew-emacs#23]
imac@iMacs-iMac ~> brew install homebrew-mode
==> Installing homebrew-mode from homebrew/homebrew-emacs
==> Installing dependencies for homebrew/emacs/homebrew-mode: homebrew/em
==> Installing homebrew/emacs/homebrew-mode dependency: homebrew/emacs/da
==> Downloading https://github.com/magnars/dash.el/archive/2.12.0.tar.gz
==> Downloading from https://codeload.github.com/magnars/dash.el/tar.gz/2.12.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c6db3a237747b02d20382a761397563d813b306c020ae28ce25a1c3915fac60f
Actual: 272b337f31edb95c5aadc8e953d522bd307dc522588f246cc9157edee10b1a76
Archive: /Library/Caches/Homebrew/dash-2.12.0.tar.gz
To retry an incomplete download, remove the file above.

**Comment by dunn** [comment]
Yeah, I asked about that in https://github.com/magnars/dash.el/issues/163.  Probably either the release was re-tagged, or I somehow committed the wrong SHA initially.

Thanks for the report!
