### ISSUE TITLE
installing php-mode generates a command requiring unfound program t

### ISSUE THREAD

**Issue by dan-mt** [Homebrew/homebrew-emacs#30]
I attempted to install php-mode via the command:
    brew install homebrew/emacs/php-mode

This was on a mac running El Capitan (10.11.1).

The command actually installed emacs and then tried to install homebrew/emacs/php-mode, but ran into problems doing 'make test'.

It failed on this sequence:
make clean
rm -f php-mode.elc php-mode-test.elc
make all
t -Q -batch -L . -f batch-byte-compile php-mode.el
make[1]: t: No such file or directory
t -Q -batch -L . -f batch-byte-compile php-mode-test.el
make[1]: t: No such file or directory
make[1]: *** [php-mode.elc] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [php-mode-test.elc] Error 1
make: *** [test] Error 2

It looks like it is trying to find a command t (so perhaps somewhere the rest of the command name got dropped?).

TIA for any clues on how to proceed.

**Comment by dunn** [comment]
That's very strange.  Can you post your `brew gist-logs php-mode`? Thanks!

**Comment by dan-mt** [comment]
https://gist.github.com/7a8fece4cde305019715
Thanks Alex for taking a look at it (and what a great command, 'brew gist-logs' !!)

**Comment by dunn** [comment]
My best guess is that somehow in your environment, `EMACS` is set to `t`.  Can you run `export EMACS=emacs` and try again?

**Comment by dan-mt** [comment]
Ah, great, and very insightful on your part Alex!

In fact, emacs itself sets EMACS to t (i believe so that any shell software you write can detect if it is running inside emacs).

I always run all my shells from inside emacs, especially for tasks like installing software (to keep a transcript, easy access to everything that went above, and all the usual reasons), so my EMACS environment variable got taken.

Anyhow, by following your suggestion, and running 'export Emacs=emacs' right before 'brew install php-mode', it sailed through.

**Comment by dunn** [comment]
Oh interesting, I didn't know that about the Emacs shell.

Glad it worked! I'll update this formula (and others) to set `EMACS` during installation.

**Comment by dunn** [comment]
This should be fixed for all formulae; thank you for the report!
