### ISSUE TITLE
ada-mode sha256 mismatch

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-emacs#35]
```
==> Installing ada-mode from homebrew/homebrew-emacs
==> Downloading http://stephe-leake.org/emacs/ada-mode/org.emacs.ada-mode-5.1.8.tar.gz
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 361b5e4f3bd8cb48a236245ce65093c361175e4ae782d0233555bd9bd294aa91
Actual: da22247244cafe9395189fcca13667448fbc6a0fd52fb0cbcd8c3b0545aaf092
Archive: /Library/Caches/Homebrew/ada-mode-5.1.8.tar.gz
To retry an incomplete download, remove the file above.
```

I sent an email on upstream’s mailing-list asking if this change was intentional: http://host114.hostmonster.com/mailman/private/emacs-ada-mode_stephe-leake.org/2015-October/000494.html (you have to be subscribed to see it).

**Comment by bfontaine** [comment]
Response from upstream:

> Sort of; there are (should be?) no content changes, but there are
probably file date changes.
> I moved to a new computer, and rebuilt the website to be sure I could.
> I do not generate hashes, so I did not notice the change. I'm guessing
the tarball includes some date info that changed.

**Comment by dunn** [comment]
Oh, thanks! Did you assign this to yourself because you were planning to commit the fix? Feel free, but I'm happy to do it too.

**Comment by bfontaine** [comment]
Yeah that was to remember myself to do it when I got back home; but I forgot about it :confused:

**Comment by dunn** [comment]
Thanks 💚
