### ISSUE TITLE
25.1-rc1 crashes

### ISSUE THREAD

**Issue by mariusk** [Homebrew/homebrew-emacs#365]
I've noticed the latest build crashes from time to time, but haven't found a reliable way to crash it yet. It has happened on a few occasions when I press C-g inside a helm buffer, so if I had to guess it has to do with "undo" functionality. I'm on macOS 10.12 beta. Will update when/if I find a reliable way to reproduce.

**Comment by mariusk** [comment]
Obviously, this was the wrong place for this report. My bad, sorry.

**Comment by ilovezfs** [comment]
@mariusk that's OK. If you do file an upstream report, you can also paste the link here so we can monitor the situation, too.

**Comment by dunn** [comment]
Yeah, there's been some talk upstream about issues on Sierra: https://lists.gnu.org/archive/html/emacs-devel/2016-07/msg01125.html

**Comment by dunn** [comment]
Oh, that's you.
