### ISSUE TITLE
Error when installing editorconfig-emacs

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-emacs#54]
When I run `brew install editorconfig-emacs`, I get the following error:

==> Installing editorconfig-emacs from homebrew/homebrew-emacs
==> Downloading https://github.com/editorconfig/editorconfig-emacs/archive/v0.4.tar.gz
Already downloaded: /home/bob/.cache/Homebrew/editorconfig-emacs-0.4.tar.gz
==> make
==> make test
Error: undefined local variable or method `elisp' for #<Formulary::FormulaNamespace0bb92030869877d6a54e829867bf1a10::EditorconfigEmacs:0x00000001eeea98>
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/bob/.linuxbrew/Library/Taps/homebrew/homebrew-emacs/Formula/editorconfig-emacs.rb:16:in `install'
/home/bob/.linuxbrew/Library/Homebrew/build.rb:129:in `block in install'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:871:in `block in brew'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:1442:in `block in stage'
/home/bob/.linuxbrew/Library/Homebrew/resource.rb:91:in `block in unpack'
/home/bob/.linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/home/bob/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/home/bob/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:1434:in `stage'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:867:in `brew'
/home/bob/.linuxbrew/Library/Homebrew/build.rb:107:in `install'
/home/bob/.linuxbrew/Library/Homebrew/build.rb:176:in `<main>'

The relevant line is `elisp.install "editorconfig.el", "editorconfig.elc"`

My gist is https://gist.github.com/70c05fc816c981a83994 . Note that it says the last commit was "4 minutes ago" - that was me cherry-picking https://github.com/Homebrew/homebrew/commit/3fff92687c2d7ef50d5274ee2ee244d30fe38e68.diff since Linuxbrew hasn't received that fix yet. I can verify that the above issue was occuring before I cherry-picked.

**Comment by dunn** [comment]
You'll need to cherry-pick https://github.com/Homebrew/homebrew/commit/65a188607e15705c7498bab63586138099a5a2dd as well; that's where I introduced `elisp` into Homebrew.

**Comment by rwhogg** [comment]
Looks like that worked! Thank you for your assistance.

I'm changing the title to reflect that this a Linuxbrew-only issue for the moment and then closing.
