### ISSUE TITLE
Emacs fails to start when installed with `--with-imagemagick`

### ISSUE THREAD

**Issue by skuro** [Homebrew/homebrew-emacs#560]
With the split between [imagemagick](https://github.com/Homebrew/homebrew-core/blob/f205a58d52cb3a1786ab6d713b3c613018454b57/Formula/imagemagick.rb) and [imagemagick@6](https://github.com/Homebrew/homebrew-core/blob/c0e8ec0b8db2552aeecbc99a78a358e9488c3cf2/Formula/imagemagick%406.rb) emacs crashes at startup:

<img width="729" alt="screen shot 2017-02-10 at 09 28 21" src="https://cloud.githubusercontent.com/assets/186085/22820385/c9fa0894-ef76-11e6-8a37-ed6c6bf4e0fc.png">

**Comment by ilovezfs** [comment]
You need to rebuild emacs from source.

**Comment by skuro** [comment]
@ilovezfs thanks for the immediate feedback, I managed to get it to work and here's the log of the commands I ran for future reference:

```bash
brew uninstall imagemagick@6 # <-- I installed it in the hope of fixing stuff
brew link imagemagick # <-- was already installed but unlinked to be able to install @6
brew uninstall emacs
brew install emacs --with-imagemagick # <-- other options were passed, but this is the only relevant one here
```

**Comment by ilovezfs** [comment]
You're welcome. Note that `imagemagick@6` is `keg_only` so

>was already installed but unlinked to be able to install @6

was not necessary.

**Comment by skuro** [comment]
it was as I did `brew link imagemagick@6` thinking that would make the dylib file pop up in the right place

**Comment by ilovezfs** [comment]
@skuro ah I see. No, you'd need to replace the `depends_on "imagemagick"` in emacs with a `depends_on "imagemagick@6"` for it to be used.
